trigger:
  - 'master'

pool:
  vmImage: 'ubuntu-18.04'

stages:

- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: MaevenSetUp
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml' 
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: 'default'
            options: compile exec:java -Dexec.mainClass="HelloWorld"

- stage: Script
  displayName: 'Script Stage'
  jobs:

    # Run a java script
    - job: ScriptFile
      steps:
        - task: ShellScript@2
          inputs:
            scriptPath: 'src/main/example.sh'

    # Run a java script inline
    - job: ScriptFileInline
      steps:
        - script: |
            echo Hello world!
      displayName: 'Scripting inline'
