name: CI

on:
  push:
      branches: [ master ]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://anamc.visualstudio.com/hello-world-java
            azure-pipeline-name: 'hello-world-java'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
            
